### PR TITLE
Including standard default expiration and fixing a bug ...

### PR DESCRIPTION
**Pull request by bryanmau1**
…where expiration could possibly be None, breaking appinfo.ParseExpiration

### CODE REVIEW

**Comment by bryanmau1** [comment]
R: @andrewsg 
CC: @jcollins-g

**Comment by andrewsg** [comment]
Looks good. Is it feasible to add a test for this case?

**Comment by bryanmau1** [comment]
Definitely feasible.  Not sure if it's worth it.  I can create a second fake app_info_external just to test the default expiration (when no expiration is mentioned in a user's yaml file).  But it'd make test code slightly harder to read.

**Comment by andrewsg** [comment]
OK, if you're not sure it's worth it then let's integrate this PR first. Thanks.

**Pull request merged**
