### PR TITLE
Re-organization

### PR DESCRIPTION
**Pull request by jonparrott**
* `multicore_runtime` has been renamed to `appengine-vmruntime` and is now its own installable Python package.
* `python_vm_runtime` has been renamed to `appengine-compat` and is now its own installable Python package.
* The subset of files that are exported from google3 are now contained in `appengine-compat/exported_appengine_sdk`.
* `gunicorn.conf.py` has been moved to `resources/gunicorn.conf.py`.
* The main `Dockerfile` has been updated to copy the two packages to `/opt` and install them at build time.
* The `dev/Dockerfile` has been deleted as it's no longer needed as the main Dockerfile now handles copying and installing the two provided packages.
* A manually-run deployment test has been added to `tests/basic_app`, it includes a `Makefile` to help with the manual task of deploying it.
* `README.md` and `LICENSE` have been added where applicable.

R: @andrewsg @bryanmau1 @jcollins-g

### CODE REVIEW

**Comment by jonparrott** [comment]
The end result here is that we've now decoupled the python packages from each other and the dockerfile.

We now have three distinct components in this repository:

- `appengine-compat` - mostly google3 code plus a `setup.py` for making it installable.
- `appengine-vmruntime` - the library that provides the entrypoint.
- `Dockerfile` - the actual runtime image.

So that means in the future we can easily see how to converge the base image with vanilla and just provide `apppengine-compat` and `appengine-vmruntime` as installable packages.

**Comment by bryanmau1** [comment]
LGTM.  Since this is a large change, won't merge the PR until others look at it

**Comment by jonparrott** [comment]
Yeah I'm not merging until @andrewsg has a chance to review and we have a plan for rolling this out.

**Comment by andrewsg** [comment]
It looks like the Dockerfile now doesn't rely on a compiled sdist, but instead just copies the entire source directory into place and installs from there. Are there any consequences to doing it that way that we need to be aware of?

**Comment by jonparrott** [comment]
It's mostly identical, it's just where the sdist happens:

Before:
1. sdist runs on host machine.
2. sdist gets copied into docker image.
3. pip untars and installs the sdist.

After:
1. source is copied to the image.
2. pip installs the source directly.

Basically we're just saving the host machine the trouble of tarring up something that pip is just going to untar. Decoupling this also makes it easier to move compat or runtime out into separate repos if we ever want to go that route.

**Comment by andrewsg** [comment]
Okay. I think it is about time to delete the "dev" Dockerfile, but note that it still did something the main Dockerfile did not -- it completed the final step of adding the user's app files and running pip install, which is normally done by the fingerprinting step. I don't think we need to solve that problem; now that you can easily use the runtime without runtime: custom, it's lived out its purpose.

**Comment by jonparrott** [comment]
Yeah, the dev dockerfile is gone. I'll be adding more tests but they'll just use `FROM` just like with the vanilla runtime.

**Comment by andrewsg** [comment]
OK. LGTM

**Comment by jonparrott** [comment]
Todo:

* Werkzeug should be in vmruntime setup.py.
* Gunicorn and futures should be in a top-level requirements.txt.
* See if vmruntime can depend on appengine-compat.

**Comment by jonparrott** [comment]
All to-do items done. Merging.

**Pull request merged**
